import type { Metadata } from "next"
//import global styles here

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AboutLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        
            <div>
                <h1>About Layout</h1>
                {children}
            </div>
        
    );
}